site_name: MKDocs

plugins:
  - mermaid2
  - search
  - social

theme:
  name: material

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/atalhox
    - icon: fontawesome/brands/twitter
      link: https://www.twitter.com/eunaoeradev
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/eunaoeradev
    - icon: fontawesome/brands/linkedin
      link: https://br.linkedin.com/in/luisfelipebrum
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/eunaoeradev
